// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/input/[dayNr].ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/js/day1.ts";
import * as $4 from "./routes/day/[dayNr].tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/DayIsland.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/input/[dayNr].ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/js/day1.ts": $3,
    "./routes/day/[dayNr].tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/DayIsland.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
